## Question 1

In [9]:
import pandas as pd
import numpy as np
import re

In [27]:
df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)
df.head(10)

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D      RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1    128521     12852     2         NaN   235.916956     1031  2017       NaN   
2     10741      1074     2         NaN   957.353840     1068  2017       NaN   
3    220011     22001     2         NaN   189.611299     1050  2017       NaN   
4     86131      8613     1  675.430817   333.447418     1040  2017       NaN   
5    227141     22714     1  482.617748   278.768063     1008  2017       NaN   
6    207941     20794     2         NaN    35.995367     1019  2017       NaN   
7    221381     22138     1  516.427723   248.916038     1008  2017       NaN   
8    182861     18286     1  313.225832   163.213401     1001  2017       NaN   
9    161121     16112     1  978.042448   718.616990     1016  2017       3.0   
10   143401     14340     2         NaN  1536.859533     1068  2017       NaN   

    HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1          2       1  ...                        NaN      NaN      NaN   
2          2       1  ...                        NaN      NaN      NaN   
3          2       3  ...                        NaN      NaN      NaN   
4          2       1  ...                        NaN      NaN      NaN   
5          2       1  ...                        NaN      NaN      NaN   
6          2       2  ...                        NaN      NaN      NaN   
7          2       3  ...                        NaN      NaN      NaN   
8          2       2  ...                        NaN      NaN      NaN   
9          1       1  ...                        NaN      NaN      NaN   
10         2       3  ...                        NaN      NaN      NaN   

    XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1       NaN      NaN      NaN          NaN          NaN  
2       NaN      NaN      NaN          NaN          NaN  
3       NaN      NaN      NaN          NaN          NaN  
4       NaN      NaN      NaN          1.0          2.0  
5       NaN      NaN      NaN          2.0          1.0  
6       NaN      NaN      NaN          NaN          NaN  
7       NaN      NaN      NaN          1.0          2.0  
8       NaN      NaN      NaN          3.0          2.0  
9       NaN      NaN      NaN          4.0          4.0  
10      NaN      NaN      NaN          NaN          NaN  

[10 rows x 453 columns]

In [15]:
df.columns

Index(['SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D', 'STRATUM', 'YEAR',
       'AGECPOXR', 'HAD_CPOX', 'AGEGRP',
       ...
       'XVRCTY2', 'XVRCTY3', 'XVRCTY4', 'XVRCTY5', 'XVRCTY6', 'XVRCTY7',
       'XVRCTY8', 'XVRCTY9', 'INS_STAT2_I', 'INS_BREAK_I'],
      dtype='object', length=453)

In [16]:
len(df)

28465

In [6]:
df['EDUC1']

1        4
2        3
3        3
4        4
5        1
        ..
28461    3
28462    2
28463    3
28464    2
28465    4
Name: EDUC1, Length: 28465, dtype: int64

In [28]:
a = df['EDUC1'].unique()
print(a)
print(len(a))

[4 3 1 2]
4


In [21]:
# 1 -> <12 years
# 2 -> =12 years
# 3 -> >12 years
# 4 -> college graduate

In [23]:
ocurrences = dict(df['EDUC1'].value_counts())
ocurrences

{4: 13656, 3: 6999, 2: 4906, 1: 2904}

In [24]:
for i in range(1,5):
    ocurrences[i] = ocurrences[i] / len(df)
    
ocurrences

{4: 0.47974705779026877,
 3: 0.24588090637625154,
 2: 0.172352011241876,
 1: 0.10202002459160373}

In [26]:
ocurrences['hich school'] = ocurrences.pop(2)
ocurrences

{3: 0.24588090637625154,
 1: 0.10202002459160373,
 'college': 0.47974705779026877,
 'hich school': 0.172352011241876}

In [32]:
# SOLUTION
# Change the path when submitting

def proportion_of_education():
    
    df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)
    
    # Step 1 : Store keys into a dictionary
    count = dict(df['EDUC1'].value_counts())
    
    # Step 2 : Calculate proportion
    for i in range(1, len(df['EDUC1'].unique()) + 1):
        count[i] = count[i] / len(df)
        
    # Replace keys 1, 2, ... for the correct names: college, less than high school, ...
    count['less than high school'] = count.pop(1)
    count['high school'] = count.pop(2)
    count['more than high school but not college'] = count.pop(3)
    count['college'] = count.pop(4)
    
    return count

    raise NotImplementedError()

print(type(proportion_of_education()))
print(len(proportion_of_education()))
print(proportion_of_education().keys())

<class 'dict'>
4
dict_keys(['less than high school', 'high school', 'more than high school but not college', 'college'])


## Question 2

In [56]:
# ever fed breast milk -> CBF_01
# total number of seasonal influenza doses -> P_NUMFLU

df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)

cols = np.array(df.columns)
cols

array(['SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D', 'STRATUM',
       'YEAR', 'AGECPOXR', 'HAD_CPOX', 'AGEGRP', 'BF_ENDR06',
       'BF_EXCLR06', 'BF_FORMR08', 'BFENDFL06', 'BFFORMFL06', 'C1R',
       'C5R', 'CBF_01', 'CEN_REG', 'CHILDNM', 'CWIC_01', 'CWIC_02',
       'EDUC1', 'FRSTBRN', 'I_HISP_K', 'INCPORAR', 'INCPORAR_I',
       'INCPOV1', 'INCQ298A', 'LANGUAGE', 'M_AGEGRP2', 'MARITAL2',
       'MOBIL_I', 'NUM_PHONE', 'NUM_CELLS_HH', 'NUM_CELLS_PARENTS',
       'RACE_K', 'RACEETHK', 'RENT_OWN', 'SEX', 'ESTIAP17', 'EST_GRANT',
       'STATE', 'D6R', 'D7', 'N_PRVR', 'PROV_FAC', 'REGISTRY',
       'VFC_ORDER', 'HEP_BRTH', 'HEP_FLAG', 'P_NUHEPX', 'P_NUHIBX',
       'P_NUHPHB', 'P_NUMDAH', 'P_NUMDHI', 'P_NUMDIH', 'P_NUMDTA',
       'P_NUMDTP', 'P_NUMFLU', 'P_NUMFLUL', 'P_NUMFLUM', 'P_NUMFLUN',
       'P_NUMHEA', 'P_NUMHEN', 'P_NUMHEP', 'P_NUMHG', 'P_NUMHHY',
       'P_NUMHIB', 'P_NUMHIN', 'P_NUMHION', 'P_NUMHM', 'P_NUMHS',
       'P_NUMIPV', 'P_NUMMCN', 'P_NUMMMR', 'P_NUMMMRX', 

In [71]:
new_df = df[['CBF_01', 'P_NUMFLU']]

new_df = new_df.dropna()
new_df = new_df[new_df['CBF_01'] != 77]
new_df = new_df[new_df['CBF_01'] != 99]

new_df

CBF_01  P_NUMFLU
4           2       3.0
5           1       0.0
7           1       0.0
8           1       0.0
9           1       0.0
...       ...       ...
28447       1       2.0
28448       2       1.0
28450       1       4.0
28453       2       2.0
28455       1       0.0

[15288 rows x 2 columns]

In [73]:
print(new_df['CBF_01'].unique())
print(new_df['P_NUMFLU'].unique())

[2 1]
[3. 0. 2. 1. 4. 5. 6.]


In [88]:
total_pos = np.sum(new_df[new_df['CBF_01'] == 1]['P_NUMFLU'])
len_pos = len(new_df[new_df['CBF_01'] == 1])
print(test1)
print(len_pos)
print('\n')
total_neg = np.sum(new_df[new_df['CBF_01'] == 2]['P_NUMFLU'])
len_neg = len(new_df[new_df['CBF_01'] == 2])
print(test2)
print(len_neg)
print('\n')
print(len_pos + len_neg)

24986.0
13291


3188.0
1997


15288


In [ ]:
# SOLUTION
# Change the path when submitting

def average_influenza_doses():
    
    import pandas as pd
    import numpy as np
    
    df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)
    
    # Step 1 : create a new dataframe with the data we are interested in
    new_df = df[['CBF_01', 'P_NUMFLU']]
    
    # Step 2 : We clean the data
    new_df = new_df.dropna()
    new_df = new_df[new_df['CBF_01'] != 77]
    new_df = new_df[new_df['CBF_01'] != 99]
    
    # Step 3 : We calculate the totals
    totalWithBreastFeed = np.sum(new_df[new_df['CBF_01'] == 1]['P_NUMFLU'])
    totalWithoutBreastFeed = np.sum(new_df[new_df['CBF_01'] == 2]['P_NUMFLU'])
    
    # Step 4 : We calculate the averages
    avgWithBreastFeed = totalWithBreastFeed / len(new_df[new_df['CBF_01'] == 1])
    avgWithoutBreastFeed = totalWithoutBreastFeed / len(new_df[new_df['CBF_01'] == 2])
    
    # Step 5 : Create the tuple
    avgDoses = (avgWithBreastFeed, avgWithoutBreastFeed)
    
    return avgDoses
    
    raise NotImplementedError()

## Question 3

In [113]:
df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)

df['P_NUMVRC']

1        NaN
2        NaN
3        NaN
4        1.0
5        0.0
        ... 
28461    NaN
28462    NaN
28463    NaN
28464    NaN
28465    NaN
Name: P_NUMVRC, Length: 28465, dtype: float64

In [128]:
# sexo del niño -> SEX
# -> 1 : Male
# -> 2 : Female

# total number of varicella doses -> P_NUMVRC
# did child ever have chicken pox -> HAD_CPOX
# -> 1 : Yes
# -> 2 : No


print(df['SEX'].unique())
print(df['P_NUMVRC'].unique())
print(df['HAD_CPOX'].unique())

[1 2]
[nan  1.  0.  2.  3.]
[ 2  1 77 99]


In [129]:
# step 1 : new dataframe with data of interest
new_df = df[['SEX', 'P_NUMVRC', 'HAD_CPOX']]
new_df

SEX  P_NUMVRC  HAD_CPOX
1        1       NaN         2
2        1       NaN         2
3        2       NaN         2
4        2       1.0         2
5        2       0.0         2
...    ...       ...       ...
28461    2       NaN         2
28462    2       NaN         2
28463    2       NaN         2
28464    2       NaN         2
28465    2       NaN         2

[28465 rows x 3 columns]

In [131]:
# Step 2: cleaning

# From HAD_CPOX
new_df = new_df.dropna()
new_df = new_df[new_df['HAD_CPOX'] != 77]
new_df = new_df[new_df['HAD_CPOX'] != 99]

# From P_NUMVRC
new_df = new_df[new_df['P_NUMVRC'] > 0]

new_df

SEX  P_NUMVRC  HAD_CPOX
4        2       1.0         2
7        2       1.0         2
11       1       1.0         2
13       1       1.0         2
17       1       2.0         2
...    ...       ...       ...
28447    2       1.0         2
28448    1       1.0         2
28450    1       1.0         2
28453    2       1.0         2
28455    2       1.0         2

[13951 rows x 3 columns]

In [132]:
print(len(new_df))
print('\n')
print(new_df['SEX'].unique())
print(new_df['P_NUMVRC'].unique())
print(new_df['HAD_CPOX'].unique())

13951


[2 1]
[1. 2. 3.]
[2 1]


In [133]:
# Step 2 : Create a new dataframefor each sex

vaccMale = new_df[new_df['SEX'] == 1]
vaccFemale = new_df[new_df['SEX'] == 2]

print(len(vaccMale))
print(len(vaccFemale))

7096
6855


In [136]:
print(vaccMale.head())
print('\n')
print(vaccFemale.head())

      SEX  P_NUMVRC  HAD_CPOX
462     1       1.0         1
688     1       1.0         1
864     1       1.0         1
1480    1       1.0         1
1907    1       1.0         1


    SEX  P_NUMVRC  HAD_CPOX
4     2       1.0         2
7     2       1.0         2
21    2       1.0         2
23    2       1.0         2
25    2       1.0         2


In [137]:
# Step 3 : Calculate ratios

RatioMale = len(vaccMale[vaccMale['HAD_CPOX'] == 1]) / len(vaccMale[vaccMale['HAD_CPOX'] == 2])
RatioFemale = len(vaccFemale[vaccFemale['HAD_CPOX'] == 1]) / len(vaccFemale[vaccFemale['HAD_CPOX'] == 2])

print(RatioMale)
print(RatioFemale)

0.009675583380762664
0.0077918259335489565


In [138]:
# SOLUTION
# Change the path when submitting

def chickenpox_by_sex():
    import pandas as pd
    import numpy as np
    
    df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)
    
    # Step 1: New dataframe with the data of interest
    new_df = df[['SEX', 'P_NUMVRC', 'HAD_CPOX']]
    
    # Step 2: Data cleaning
    # HAD_CPOX
    new_df = new_df.dropna()
    new_df = new_df[new_df['HAD_CPOX'] != 77]
    new_df = new_df[new_df['HAD_CPOX'] != 99]
    
    # P_NUMVRC
    new_df = new_df[new_df['P_NUMVRC'] > 0]
    
    # Step 3: DataFrame for each sex
    VaccMale = new_df[new_df['SEX'] == 1]
    VaccFemale = new_df[new_df['SEX'] == 2]
    
    # Step 4: Calculate ratios: had CPOX / didn't have CPOX
    RatioMale = len(vaccMale[vaccMale['HAD_CPOX'] == 1]) / len(vaccMale[vaccMale['HAD_CPOX'] == 2])
    RatioFemale = len(vaccFemale[vaccFemale['HAD_CPOX'] == 1]) / len(vaccFemale[vaccFemale['HAD_CPOX'] == 2])
    
    results = {'male' : RatioMale, 'female' : RatioFemale}
    
    return results
    
    raise NotImplementedError()
    
chickenpox_by_sex()

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

## Question 4

In [140]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
                   "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    return corr

    # YOUR CODE HERE
    raise NotImplementedError()
    
corr_chickenpox()

0.11626078345427274

In [142]:
print(corr_chickenpox() < 1.0)
print(corr_chickenpox() > -1.0)

True
True


In [144]:
df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)
    
# Step 1: New dataframe with the data of interest
new_df = df[['P_NUMVRC', 'HAD_CPOX']]

# Step 2: Data cleaning
# HAD_CPOX
new_df = new_df.dropna()
new_df = new_df[new_df['HAD_CPOX'] != 77]
new_df = new_df[new_df['HAD_CPOX'] != 99]

print(new_df['P_NUMVRC'].unique())
print(new_df['HAD_CPOX'].unique())

[1. 0. 2. 3.]
[2 1]


In [151]:
print(new_df.head())
print('\n')
print(len(new_df))

   P_NUMVRC  HAD_CPOX
4       1.0         2
5       0.0         2
7       1.0         2
8       0.0         2
9       0.0         1


15286


In [156]:
print(len(new_df["HAD_CPOX"]))
print(len(new_df["P_NUMVRC"]))

15286
15286


In [155]:
import scipy.stats as stats

corr, pval=stats.pearsonr(new_df["HAD_CPOX"],new_df["P_NUMVRC"])

print(corr)

0.07044873460148


In [159]:
# SOLUTION

def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    #df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
                   #"num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    # here is some stub code to actually run the correlation
    #corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    # return corr

    # Step 1: Import data
    df = pd.read_csv('/Users/jonathansuarezcaceres/Downloads/1_Data Science/Intro to DS with Python/NISPUF17.csv',
                index_col = 0)
    
    # Step 2: New dataframe with the data of interest
    new_df = df[['P_NUMVRC', 'HAD_CPOX']]

    # Step 3: Data cleaning
    new_df = new_df.dropna()
    new_df = new_df[new_df['HAD_CPOX'] != 77]
    new_df = new_df[new_df['HAD_CPOX'] != 99]
    
    # Step 4: correlation calculation
    corr, pval=stats.pearsonr(new_df["HAD_CPOX"],new_df["P_NUMVRC"])

    return corr
    
    raise NotImplementedError()
    
corr_chickenpox()

0.07044873460148